import "./globals.css";
import 'font-awesome/css/font-awesome.min.css';

import Header from "@/app/comopnents/Header";
import Footer from "@/app/comopnents/Footer";
import {Providers} from "@/app/store/Providers";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <Providers>
            <html lang="en">
            <body className="flex flex-col min-h-screen">
            {/* Header */}
            <Header/>

            {/* Main Content (children) */}
            <main className="flex-1 container mx-auto p-4">
                {children}
            </main>
            {/* Footer */}
            <Footer/>
            </body>
            </html>
        </Providers>
    );
}
